### ISSUE TITLE
Dependency of framework .NET

### ISSUE THREAD

**Issue by HugoAVaz** [sungaila/PDFtoZPL#10]
![image](https://user-images.githubusercontent.com/60146011/143020131-156d58b3-fb67-4653-aef7-051a0f552b91.png)

Can't this ve overcome and just define the class for .net standard? So this can be used in other systems?

For example using:
![image](https://user-images.githubusercontent.com/60146011/143020507-f1400bd2-7260-409e-892f-bd7f25a8867b.png)

**Comment by sungaila** [comment]
Hi @HugoAVaz,

thanks for leaving your feedback! There are a few reasons I decided to not use .NET Standard 2.0 for this project:

1. The NuGet package contains native libraries and .NET Framework treats these different from .NET (Core). E.g. the runtimes folder is not supported in .NET Framework and must be handled manually. I haven't checked whether .NET Standard will unify this behavior though ...
2. Some classes are missing in .NET Standard 2.0 like `IAsyncEnumerable<T>` and `SupportedOSPlatformAttribute`.
3. With .NET 5.0 I can explicitly state that only Windows, macOS and Linux are supported (there are no PDFium builds for other platforms yet). However, .NET Standard 2.0 allows for using Xamarin and UWP ... but I cannot support these.

Is there a unsupported platform (e.g. Android) or framework (e.g. Mono) you wish to use PDFtoZPL on?

Greetings
David S.
