### ISSUE TITLE
ZPL to PDF

### ISSUE THREAD

**Issue by sid80210** [sungaila/PDFtoZPL#15]
Hi,

there is a way to do the conversion from ZPL to PDF?

Thanks

**Comment by sungaila** [comment]
Hey @sid80210,

this library does not support conversion from ZPL to PDF.

If you want to convert manually you can use the [Labelary Online ZPL Viewer](http://labelary.com/viewer.html). If you wish to automate this, you might want to use the [Labelary ZPL Web Service](http://labelary.com/service.html#csharp).

There might .NET libraries to do the conversion locally but I haven't searched for one yet.

Greetings,
David
