### ISSUE TITLE
Why change to Skiasharp?

### ISSUE THREAD

**Issue by GitOguz** [sungaila/PDFtoZPL#16]
Nvm solved my self.

**Comment by sungaila** [comment]
I can see you solved this problem yourself but I'd like to add the motivation for anyone else wondering:

[.NET 6 and newer will not support System.Drawing.Common for platforms other than Windows.](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) Right now, it's just compiler warnings but this will become worse in future releases.

[SkiaSharp](https://github.com/mono/SkiaSharp) is maintained by Microsoft/Xamarin so it felt like the safest choice.

**Comment by GitOguz** [comment]
Thank you for your reply.
