### ISSUE TITLE
Feature Requests: Output in Z64 Format and Only ZPL ^GF Element

### ISSUE THREAD

**Issue by thevarium** [sungaila/PDFtoZPL#18]
Output in Z64 Format:
I know Zebra has a compressed Z64 format which just compresses the content you are already responding with. Do you have any plans on supporting that additional logic so the output is a smaller payload?
Only ZPL ^GF Element:
Can we add an option to only output the ^GF element so I can utilize it in my ZPL without having to remove the other characters?

**Comment by sungaila** [comment]
Hi @thevarium,

>Output in Z64 Format
You mean the Base64 encoding and LZ77 compression of the bitmap? I'll take a look into the Zebra documentation, shouldn't be too complex to implement ...

>Only ZPL ^GF Element
Good idea, I'll add a method for that.

**Comment by sungaila** [comment]
Hey @thevarium, could you please give [PDFtoZPL 3.2.0](https://www.nuget.org/packages/PDFtoZPL/3.2.0) a try?

To retain backward compatibility, I introduced the optional parameters `encodingKind` and `graphicFieldOnly`. Now you can call any conversion method like this:

```csharp
var result = PDFtoZPL.Conversion.ConvertPdfPage(
	pdfStream,
	encodingKind: PDFtoZPL.Conversion.BitmapEncodingKind.Base64Compressed,
	graphicFieldOnly: true);
```

Please let me know if this is what you needed.

**Comment by thevarium** [comment]
This is amazing! I am testing in bulk but my initial test look perfect. Thank you! Thank you! Thank you!
