### ISSUE TITLE
Linux x86-64 support issue

### ISSUE THREAD

**Issue by estebandeleo** [sungaila/PDFtoZPL#2]
Hello! I'm having problems with the Linux compatibility of the library in my NetCore app.

I have tested the **PDFium** and also the **Pdfiumviewer** packages in the past, but had the compatibility issue with Linux since my application runs on a dockerized ubuntu image. I wanted to try **PDFtoZPL** package exclusively because of the Linux support but it is not working for me.

My application is a NetCore 3.1 webapi which runs on the following docker image: **_mcr.microsoft.com/dotnet/core/sdk:3.1-bionic_**

While running Unit Tests in our ADO pipeline, looks like it fails to load the neccessary depencies libraries, as happened with the PDFIum and pdfviewer packages.

**This is the error stacktrace:**
```
test-unit_1  |   Error Message:
test-unit_1  |    System.TypeInitializationException : The type initializer for 'PDFtoZPL.PdfiumViewer.NativeMethods' threw an exception.
test-unit_1  | ---- System.DllNotFoundException : Unable to load shared library 'kernel32' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32: cannot open shared object file: No such file or directory
test-unit_1  |   Stack Trace:
test-unit_1  |      at PDFtoZPL.PdfiumViewer.NativeMethods.FPDF_InitLibrary()
test-unit_1  |    at PDFtoZPL.PdfiumViewer.PdfLibrary..ctor()
test-unit_1  |    at PDFtoZPL.PdfiumViewer.PdfLibrary.EnsureLoaded()
test-unit_1  |    at PDFtoZPL.PdfiumViewer.PdfFile..ctor(Stream stream, String password)
test-unit_1  |    at PDFtoZPL.PdfiumViewer.PdfDocument..ctor(Stream stream, String password)
test-unit_1  |    at PDFtoZPL.PdfiumViewer.PdfDocument.Load(Stream stream, String password)
test-unit_1  |    at PDFtoZPL.Conversion.ConvertPdfPage(Stream pdfStream, String password, Int32 page, Int32 dpi, Nullable`1 width, Nullable`1 height)
test-unit_1  |    at PDFtoZPL.Conversion.ConvertPdfPage(Byte[] pdfAsByteArray, String password, Int32 page, Int32 dpi, Nullable`1 width, Nullable`1 height)
```

Possible workarounds I tried with no success:
- Running **apt-get update && apt-get install -y libgdiplus** in the Dockerfile
- Copying the native linux binaries in the Dockerfile (libpdfium.so, and also tried some other libraries)
- Manually copying the binaries in my .Net projects

**Comment by sungaila** [comment]
Hey there, I just [uploaded a new version](https://www.nuget.org/packages/PDFtoZPL/1.3.0) that should fix the dependencies issue. Make sure to have libgdiplus installed in your docker container.

Please let me know if that helped.

**Comment by estebandeleo** [comment]
Hello David!
First of all thank you very much for taking care of the issue and fixing it quickly. After upgrading the package to version 1.3.1 and installing "libgdiplus" lib in my Docker container, it worked perfectly!

Greetings from Buenos Aires, Argentina! :D

**Comment by sungaila** [comment]
Glad it worked out! :)
