### ISSUE TITLE
Unable to find an entry point named 'FPDF_InitLibrary' in DLL 'pdfium.dll'.

### ISSUE THREAD

**Issue by alvinrdaroy** [sungaila/PDFtoZPL#22]
Hello,

I am getting this error when I try to call the PDFtoZPL.Conversion.ConvertPdfPage().

'Unable to find an entry point named 'FPDF_InitLibrary' in DLL 'pdfium.dll'.'

Any idea what causing the issue.

Thanks in advance.

Alvin

**Comment by sungaila** [comment]
Hi @alvinrdaroy,

Could you please check the version of the pdfium.dll file in your output directory? It should be **105.0.5187.0**.

The error message implies that pdfium.dll was found but the containing FPDF_InitLibrary function was not.

A version mismatch is my first guess. Does your project use its own pdfium library from an other source?

**Comment by alvinrdaroy** [comment]
Hi @sungaila,

Thanks for the reply.
Yes, i think the pdfium version is correct from my output directory. 

bin\runtimes\win-x86\native

![image](https://user-images.githubusercontent.com/60081163/192915183-1e5f9952-c2c2-4112-bcb5-e3c37cddc06d.png)


Alvin

**Comment by alvinrdaroy** [comment]
Hi @sungaila ,

I have this Pdfium.Net.SDK installed in my project. 
![image](https://user-images.githubusercontent.com/60081163/192916236-86bf27cc-9492-4677-a10d-2368d1046f07.png)
