### ISSUE TITLE
Width and Height

### ISSUE THREAD

**Issue by KimoGao** [sungaila/PDFtoZPL#23]
I'm tring to resize the pdf to 4*6 inch, but looks like the function is using pixel. How can I use inch to resize the label? Thank you so much.

**Comment by sungaila** [comment]
Hello @KimoGao,

the conversion methods have a `dpi` parameter that defaults to **203**. If you keep the default dpi value you would have to set `width` to **812** (203 * 4) and `height` to **1218** (203 * 6).

**Comment by sungaila** [comment]
Please reopen this issue if I didn't answer your question.
