### ISSUE TITLE
System.DllNotFoundException pdfium

### ISSUE THREAD

**Issue by federico-caselli-ciar** [sungaila/PDFtoZPL#25]
I've installed the nuget on a c# winforms VS2022 project.

When the users try to use the executable, which was deployed via clickonce, they get the following error:

Unable to load DLL 'pdfium.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Stack trace **
System.DllNotFoundException: Unable to load DLL 'pdfium.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

   in PDFtoImage.PdfiumViewer.NativeMethods.Imports.FPDF_InitLibrary()
   in PDFtoImage.PdfiumViewer.NativeMethods.FPDF_InitLibrary()
   in PDFtoImage.PdfiumViewer.PdfLibrary.EnsureLoaded()
   in PDFtoImage.PdfiumViewer.PdfFile..ctor(Stream stream, String password, Boolean disposeStream)
   in PDFtoImage.PdfiumViewer.PdfDocument..ctor(Stream stream, String password, Boolean disposeStream)
   in PDFtoImage.PdfiumViewer.PdfDocument.Load(Stream stream, String password, Boolean disposeStream)
   in PDFtoImage.Conversion.ToImage(Stream pdfStream, Boolean leaveOpen, String password, Int32 page, Int32 dpi, Nullable`1 width, Nullable`1 height, Boolean withAnnotations, Boolean withFormFill)
   in PDFtoZPL.Conversion.ConvertPdfPage(Stream pdfStream, Boolean leaveOpen, String password, Int32 page, Int32 dpi, Nullable`1 width, Nullable`1 height, Boolean withAnnotations, Boolean withFormFill, BitmapEncodingKind encodingKind, Boolean graphicFieldOnly)
   in PDFtoZPL.Conversion.ConvertPdfPage(Byte[] pdfAsByteArray, String password, Int32 page, Int32 dpi, Nullable`1 width, Nullable`1 height, Boolean withAnnotations, Boolean withFormFill, BitmapEncodingKind encodingKind, Boolean graphicFieldOnly)
   
**OS information**
same error on Windows 10 Pro 1909 and Windows 10 Pro 21H2 so far

**Comment by sungaila** [comment]
Hi @federico-caselli-ciar,

what are your ClickOnce settings? I couldn't replicate your issue with a simple WinForms app and ClickOnce using default settings (just clicking forward on the settings wizard).

**Comment by federico-caselli-ciar** [comment]
Hi,

as a workaround I've just installed FreeSpire Pdf NuGet which I'm using to convert the pdf to image, before converting to zpl.
![ClickOnceSettings04](https://user-images.githubusercontent.com/49472415/215998249-807a106e-5ce3-4920-9a00-06801bd59f94.png)
![ClickOnceSettings05](https://user-images.githubusercontent.com/49472415/215998259-afa3b794-4839-47f0-be35-6fe283377803.png)
![ClickOnceSettings06](https://user-images.githubusercontent.com/49472415/215998263-1b65887c-0c28-453b-85e5-06445a53a2df.png)
![ClickOnceSettings07](https://user-images.githubusercontent.com/49472415/215998265-85ecc881-1e86-41c0-843e-d3d1aaedc6da.png)
![ClickOnceSettings08](https://user-images.githubusercontent.com/49472415/215998269-8717617e-a4ff-46cf-bdc3-5449791b9976.png)
![ClickOnceSettings09](https://user-images.githubusercontent.com/49472415/215998273-0c295c96-b67c-4921-b04e-e4e520023812.png)
![ClickOnceSettings10](https://user-images.githubusercontent.com/49472415/215998280-af34809c-e4d3-4290-9286-40041b71ef82.png)
![ApplicationSettings](https://user-images.githubusercontent.com/49472415/215998284-740edb4b-8e43-4026-baf2-e3bfcde2645e.png)
![BuildSettings](https://user-images.githubusercontent.com/49472415/215998286-033f6898-c784-409a-954a-7b8d36d64177.png)
![Nugets](https://user-images.githubusercontent.com/49472415/215998288-66be94f2-b179-4c10-8ff7-140d4b4edc01.png)
![ClickOnceSettings01](https://user-images.githubusercontent.com/49472415/215998291-b32c4b2c-792b-4bb1-b092-082b8a4dec15.png)
![ClickOnceSettings02](https://user-images.githubusercontent.com/49472415/215998292-93cc45c6-b736-40f6-a807-7283ccbed098.png)
![ClickOnceSettings03](https://user-images.githubusercontent.com/49472415/215998296-ce7ef52c-15b2-414e-ae74-ebc9066738f3.png)

Screenshots attached.

**Comment by sungaila** [comment]
Please revert back to [bblanchon.PDFium.Win32 105.0.5187](https://www.nuget.org/packages/bblanchon.PDFium.Win32/105.0.5187), this should fix your issue.

The newer bblanchon NuGet packages have changed for legacy .NET Framework projects but PDFtoZPL has not been updated yet.

**Comment by sungaila** [comment]
@federico-caselli-ciar You can also test the [PDFtoZPL 3.3.0](https://www.nuget.org/packages/PDFtoZPL/3.3.0) release.

**Comment by sungaila** [comment]
Please reopen this issue if it isn't fixed by now.
