### ISSUE TITLE
Label position error on print

### ISSUE THREAD

**Issue by rafageraldo** [sungaila/PDFtoZPL#32]
Hey,
I'm receiving a pdf in base64 via API, I convert it to ZPL using Conversion.ConvertPdfPage, the return is sent to the Zebra printer.
But the label is coming out with a margin space that I can't adjust, I've tried changing the DPI, width and height and even the withAspectRatio.
I used the site http://labelary.com/viewer.html to validate that it wasn't a printer problem, and the same thing happens.
Is there any adjustment that you recommend making?
My email is rafa.geraldo@gmail.com, if you want to keep in touch.

Thanks
![label](https://github.com/sungaila/PDFtoZPL/assets/110073015/7698eb9c-1700-4f65-aa2d-bae4ac989c5f)

**Comment by sungaila** [comment]
Hi @rafageraldo,

is the image below your test input? It looks like the image itself has margins (red are the image borders and cyan is the conent):

![259419975-7698eb9c-1700-4f65-aa2d-bae4ac989c5f with Margin](https://github.com/sungaila/PDFtoZPL/assets/12021771/b8aac263-3691-4348-80a8-79921c367401)

This library has no options to crop images, is there a way for you to clean up the images before using PDFtoZPL?

**Comment by rafageraldo** [comment]
Thanks for the answer,
The image is the result after converting to ZPL.

I'm adding the original PDF file and the base64.
When printing via windows, it comes out correctly on the label.
[label_zpl.txt](https://github.com/sungaila/PDFtoZPL/files/12305938/label_zpl.txt)
[label_base64.txt](https://github.com/sungaila/PDFtoZPL/files/12305939/label_base64.txt)
[Etiqueta_PDF_982023_142616.pdf](https://github.com/sungaila/PDFtoZPL/files/12305940/Etiqueta_PDF_982023_142616.pdf)

**Comment by sungaila** [comment]
So this issue does not happen on Windows machines? What OS did you test this on? Linux in a Docker container or something else?

Does the output ZPL code differ between Windows and this other OS?

**Comment by rafageraldo** [comment]
I am using Windows 10.
The error does not happen when I print the pdf file directly from adobe reader or google chrome.

I'll try to convert the file from PDF to PNG to see if that works.
