### ISSUE TITLE
The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.

### ISSUE THREAD

**Issue by syleong** [sungaila/PDFtoZPL#38]
Hi,

I just installed the newest version of PdfToZpl, I got this error

The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.

Stack Trace
   at PDFtoImage.PdfiumViewer.PdfDocument.Render(Int32 page, Int32 width, Int32 height, Single dpiX, Single dpiY, PdfRotation rotate, PdfRenderFlags flags, Boolean renderFormFill)
   at PDFtoImage.Conversion.<ToImages>d__31.MoveNext()
   at PDFtoZPL.Conversion.<ConvertPdf>d__7.MoveNext()
   at PDFtoZPL.Conversion.<ConvertPdf>d__5.MoveNext()

The InnerException is
   Thread was being aborted.

Source:
   mscorlib

Stack Trace
   at System.Diagnostics.Debugger.NotifyOfCrossThreadDependencySlow()
   at System.Diagnostics.Debugger.NotifyOfCrossThreadDependency()
   at System.Lazy`1.get_Value()
   at SkiaSharp.SkiaApi.GetSymbol[T](String name)
   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
   at SkiaSharp.SKImageInfo..cctor()

Any idea what causing the issue.

Thanks in advance.

Best Regards
Joe

**Comment by sungaila** [comment]
Hi @syleong, is this the full exception message? Or is there an inner exception like `DllNotFoundException`?

This error message might be about your app being unable to load the `libSkiaSharp` library.

**Comment by syleong** [comment]
Thanks for your prompt response.

May I know where should I get the libSkiaSharp.dll? Should I just place the libSkiaSharp.dll directory as pdfium.dll ? Thanks

**Comment by sungaila** [comment]
You don't have to do that manually, there should be a `libSkiaSharp.dll` in the same folder as `pdfium.dll`. If there isn't, this might be the cause of the issue and we have to check why it wasn't put there automatically.

**Comment by syleong** [comment]
Hi,

The InnerException is Thread was being aborted. Hope below images can show you where the exception thrown. Thanks

<img width="542" alt="image" src="https://github.com/sungaila/PDFtoZPL/assets/14015788/3c7c0d61-aa85-4231-937a-3b403bb1ee63">

<img width="610" alt="image" src="https://github.com/sungaila/PDFtoZPL/assets/14015788/9d93ffa1-c8e8-403d-bd69-6a7d05accb9b">

**Comment by syleong** [comment]
> You don't have to do that manually, there should be a `libSkiaSharp.dll` in the same folder as `pdfium.dll`. If there isn't, this might be the cause of the issue and we have to check why it wasn't put there automatically.

Hi,

When I Nuget the Pdf2ZPL the pdfium.dll is in bblanchon.PDFium.Win32.112.0.5567 and libSkiaSharp.dll is in SkiaSharp.NativeAssets.Win32.2.88.3. 

I have to copy the PIFium.dll into the BIN folder of my asp.net otherwise it is not able to load the pdfium.dll. Thanks

**Comment by sungaila** [comment]
Does it work if you copy the `libSkiaSharp.dll` into your bin folder as well? Are you using ASP.NET Core or the older ASP.NET (for .NET Framework)?

**Comment by syleong** [comment]
> Does it work if you copy the `libSkiaSharp.dll` into your bin folder as well? Are you using ASP.NET Core or the older ASP.NET (for .NET Framework)?

It does not work. I still get the same error. I am using the older ASP.NET. 

It seems that below Method threw the exception in one of the image above. 

Method System.Reflection.MemberInfo.get_CustomAttributes cannot be called in this context.

**Comment by syleong** [comment]
Hi,

Do I need to Nuget PDFuimViewer?

**Comment by sungaila** [comment]
Could you please this code into your project and check if the same exception is thrown?

```csharp
var info = new SKImageInfo();
info.Width = 200;
```

And no, you don't need any other nuget packages.

**Comment by syleong** [comment]
Hi,

The info.width is set to 200 without any problem.

I build a simple console with PDFtoZPL 3.6.2 Nuget package, can you please let me know what is missing? Thanks in advance

https://drive.google.com/file/d/1R5f7DUXX7xaQbPrfVTzbS-MZt4iqRyhE/view?usp=sharing

**Comment by syleong** [comment]
Hi @sungaila 

With he initialization of the SKImageInfo. It works as it shown below.

<img width="752" alt="image" src="https://github.com/sungaila/PDFtoZPL/assets/14015788/ee6823d9-ee54-470c-bdad-d180ed38e2af">

However, if I comment the initialization and rerun the debugger, it will thrown an error 

<img width="495" alt="image" src="https://github.com/sungaila/PDFtoZPL/assets/14015788/946da95a-e7c3-494d-abeb-f078d943afc3">

**Comment by sungaila** [comment]
I am not sure if there is much I can do about it. I included some special code for ASP.NET to load `pdfium.dll` properly (and it works as you said).

SkiaSharp, however, is referenced as a NuGet package and loading `libSkiaSharp.dll` is their own responsibility.

Can you live with a workaround like this?

```
Dim _ = GetType(SkiaSharp.SKImageInfo)

Dim data() as Byte = File.ReadAllBytes("D:\UK496192657.pdf")
Dim zplString = PDFtoZPL.Conversion.ConvertPdf(data)
```

**Comment by sungaila** [comment]
Please reopen this issue if the workaround above isn't working for you.
