### ISSUE TITLE
Content bounding issue after updating to 5.0

### ISSUE THREAD

**Issue by brettzook** [sungaila/PDFtoZPL#50]
### PDFtoZPL version

5.0.0

### OS

Windows

### OS version

Windows 10

### Architecture

x64

### Framework

.NET (Core)

### App framework

ASP.NET Core 7.0

### Detailed bug report

I updated to version 5.0 this morning (from 4.0) and found a difference in behavior I wasn't expecting.

Previously I had this line of code:
```
var zpl = PDFtoZPL.Conversion.ConvertPdfPage(docServerResponse.PdfBytes, rotation: PDFtoImage.PdfRotation.Rotate90);
```

I was aware of the breaking change in 5.0, so I changed that line to this:
```
var zpl = PDFtoZPL.Conversion.ConvertPdfPage(docServerResponse.PdfBytes, pdfOptions: new PDFtoImage.RenderOptions { 
  Rotation = PDFtoImage.PdfRotation.Rotate90
});
```

The issue is that when the `zpl` data is sent to a label printer, the content is enlarged and way outside the bounds of the label. The content that does appear on the label is anchored from the lower left corner of the rotated PDF content. In other words, the top and right edges of the content I'm expecting to see are outside the bounds of the label.

I adjusted the code to pass in a `Dpi` value that I arrived at by trial and error in order to make the label look the way it did previously, but wasn't sure if there's a better approach, or if the `Dpi` value was intended to be necessary.
```
var zpl = PDFtoZPL.Conversion.ConvertPdfPage(docServerResponse.PdfBytes, pdfOptions: new PDFtoImage.RenderOptions {
  Rotation = PDFtoImage.PdfRotation.Rotate90,
  Dpi = 204  // arrived at this value by trial and error
});
```

**Comment by sungaila** [comment]
Hi @brettzook, you are right about the changed behavior.

In 4.x the default DPI value was `203`. In 5.x this value was changed to `300` (the default value in `RenderOptions`).

I've forgotten to document this breaking change in the release notes. In your case this should generate ZPL code as it used to:

```csharp
var zpl = PDFtoZPL.Conversion.ConvertPdfPage(docServerResponse.PdfBytes, pdfOptions: new PDFtoImage.RenderOptions { 
	Dpi = 203,
	Rotation = PDFtoImage.PdfRotation.Rotate90
});
```

**Comment by sungaila** [comment]
@brettzook [PDFtoZPL 5.0.1](https://www.nuget.org/packages/PDFtoZPL/5.0.1) reverts the default `Dpi` back to `203`.

Unfortunately, to achive this the parameters had to be changed again: `PDFtoImage.RenderOptions` became `PDFtoZPL.PdfOptions`. This is a breaking change (once again) but hopefully the last one.

Your code from above must be changed to

```csharp
var zpl = PDFtoZPL.Conversion.ConvertPdfPage(docServerResponse.PdfBytes, pdfOptions: new PDFtoZPL.PdfOptions { 
	Rotation = PDFtoImage.PdfRotation.Rotate90
});
```

Please give it a try. No more messing with default values, I promise! ;-)

**Comment by brettzook** [comment]
Works great, thank you!
