### ISSUE TITLE
Support for increasing the number of printed copies

### ISSUE THREAD

**Issue by LandryOnl** [sungaila/PDFtoZPL#59]
### Detailed feature request

as titile,i hope add the number of printed cpoies in zploptions and add ^PQ{print number},0,1,Y zpl command;in my fork;define the datatype of int for printcopies in zploptions ,and in function name createbitmapimp,add zpl command such as  ^PQ{print number},0,1,Y ,can you do it?
such as below image 

![image](https://github.com/sungaila/PDFtoZPL/assets/86591013/68c6bd7e-e214-421b-9807-176678c73306)
![image](https://github.com/sungaila/PDFtoZPL/assets/86591013/d8b6c290-2c80-4e79-aaae-60dc6e4618ca)

**Comment by sungaila** [comment]
Hi @LandryOnl,

thank you for your suggestion! This is a good idea, I'll add this and will get back to you.

**Comment by LandryOnl** [comment]
> Hi @LandryOnl,
> 
> thank you for your suggestion! This is a good idea, I'll add this and will get back to you.

I look forward to your reply

**Comment by sungaila** [comment]
@LandryOnl [PDFtoZPL 5.0.3](https://www.nuget.org/packages/PDFtoZPL/5.0.3) has been released. You can use the new parameter `PrintQuantity` like this:

```csharp
var zpl = ConvertPdfPage(pdfStream, zplOptions: new(PrintQuantity: 30))
```

**Comment by LandryOnl** [comment]
> @LandryOnl [PDFtoZPL 5.1.0](https://www.nuget.org/packages/PDFtoZPL/5.1.0) has been released. You can use the new parameter `PrintQuantity` like this:
> 
> ```cs
> var zpl = ConvertPdfPage(pdfStream, zplOptions: new(PrintQuantity: 30))
> ```

ok,

**Comment by sungaila** [comment]
Please reopen this issue if the new `PrintQuantity` parameter is not working for you.
