### ISSUE TITLE
Can't find pdfuim .dll

### ISSUE THREAD

**Issue by MyHouseIsBig** [sungaila/PDFtoZPL#6]
When I use the `PDFtoZPL.Conversion.ConvertPdfPage()` method in a console application It works as expected but when I use it in a MVC Web Application I receive the following error:

> Failed to load DLL 'pdfium.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E).

I left the platform as default.

**Stack trace**

> [DllNotFoundException: Impossibile caricare la DLL 'pdfium.dll': Impossibile trovare il modulo specificato. (Eccezione da HRESULT: 0x8007007E).]
>    PDFtoImage.PdfiumViewer.Imports.FPDF_InitLibrary() +0
>    PDFtoImage.PdfiumViewer.NativeMethods.FPDF_InitLibrary() +58
>    PDFtoImage.PdfiumViewer.PdfLibrary.EnsureLoaded() +96
>    PDFtoImage.PdfiumViewer.PdfFile..ctor(Stream stream, String password) +14
>    PDFtoImage.PdfiumViewer.PdfDocument..ctor(Stream stream, String password) +34
>    PDFtoImage.PdfiumViewer.PdfDocument.Load(Stream stream, String password) +36
>    PDFtoImage.Conversion.ToImage(Stream pdfStream, String password, Int32 page, Int32 dpi, Nullable`1 width, Nullable`1 height, Boolean withAnnotations, Boolean withFormFill) +87
>    PDFtoZPL.Conversion.ConvertPdfPage(Stream pdfStream, String password, Int32 page, Int32 dpi, Nullable`1 width, Nullable`1 height, Boolean withAnnotations, Boolean withFormFill) +70
>    PDFtoZPL.Conversion.ConvertPdfPage(Byte[] pdfAsByteArray, String password, Int32 page, Int32 dpi, Nullable`1 width, Nullable`1 height, Boolean withAnnotations, Boolean withFormFill) +118
>    PDFtoZPL.Conversion.ConvertPdfPage(String pdfAsBase64String, String password, Int32 page, Int32 dpi, Nullable`1 width, Nullable`1 height, Boolean withAnnotations, Boolean withFormFill) +70
>    carrierintegration_dev.Controllers.Utils.General.Logs.GetBasicLogs(String id) in C:\Users\maxim.palotti.USCO\source\repos\carrierintegration-dev\carrierintegration-dev\Controllers\Utils\General\Logs.cs:145
>    lambda_method(Closure , ControllerBase , Object[] ) +102
>    System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14
>    System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +157
>    System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +27
>    System.Web.Mvc.Async.<>c.<BeginInvokeSynchronousActionMethod>b__9_0(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +22
>    System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +29
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
>    System.Web.Mvc.Async.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0() +58
>    System.Web.Mvc.Async.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2() +228
>    System.Web.Mvc.Async.<>c__DisplayClass7_0.<BeginInvokeActionMethodWithFilters>b__1(IAsyncResult asyncResult) +10
>    System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
>    System.Web.Mvc.Async.<>c__DisplayClass3_6.<BeginInvokeAction>b__4() +35
>    System.Web.Mvc.Async.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult) +100
>    System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
>    System.Web.Mvc.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState) +11
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
>    System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +45
>    System.Web.Mvc.<>c.<BeginExecute>b__151_2(IAsyncResult asyncResult, Controller controller) +13
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
>    System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
>    System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
>    System.Web.Mvc.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState) +28
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
>    System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
>    System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
>    System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9850009
>    System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +50
>    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +163

**OS information**
- Windows
- x64
- Windows 10

**Comment by sungaila** [comment]
Hi @MyHouseIsBig,

how does your output directory look like? It should be something like this:

- YourApplication.exe
- PDFtoImage.dll
- PDFtoZPL.dll
- runtimes
  - win-x64
    - native
      - pdfium.dll

PDFtoZPL uses the relative path `runtimes\win-x64\native\pdfium.dll` to find it.

**Comment by sungaila** [comment]
Hey @MyHouseIsBig, could you please check if this problem was fixed in [2.1.1](https://www.nuget.org/packages/PDFtoZPL/2.1.1)?

**Comment by sungaila** [comment]
Please reopen this issue if the [latest NuGet package](https://www.nuget.org/packages/PDFtoZPL) does not fix this problem.

**Comment by Shovinus** [comment]
I am having the same issue with the latest version - 2.2.1

**Comment by sungaila** [comment]
Hi @Shovinus,

how does your output dictionary look like? Is the pdfium.dll in the base dictionary or in the runtimes folder? Can you share the Exception stack trace?

**Comment by Shovinus** [comment]
Hi @sungaila , thank you for the fast response, I am running .NET Framework 4.7.2.

```
 at PDFtoImage.PdfiumViewer.NativeMethods.Imports.FPDF_InitLibrary()
   at PDFtoImage.PdfiumViewer.NativeMethods.FPDF_InitLibrary()
   at PDFtoImage.PdfiumViewer.PdfLibrary.EnsureLoaded()
   at PDFtoImage.PdfiumViewer.PdfFile..ctor(Stream stream, String password)
   at PDFtoImage.PdfiumViewer.PdfDocument..ctor(Stream stream, String password)
   at PDFtoImage.PdfiumViewer.PdfDocument.Load(Stream stream, String password)
   at PDFtoImage.Conversion.ToImage(Stream pdfStream, String password, Int32 page, Int32 dpi, Nullable`1 width, Nullable`1 height, Boolean withAnnotations, Boolean withFormFill)
   at PDFtoZPL.Conversion.ConvertPdfPage(Stream pdfStream, String password, Int32 page, Int32 dpi, Nullable`1 width, Nullable`1 height, Boolean withAnnotations, Boolean withFormFill)
   at PDFtoZPL.Conversion.ConvertPdfPage(Byte[] pdfAsByteArray, String password, Int32 page, Int32 dpi, Nullable`1 width, Nullable`1 height, Boolean withAnnotations, Boolean withFormFill)
```
Stacktrace after call from my function.

As for the output dictionary, I assume you mean directory?

There is nothing like this, checking nuget though I can see it has added your PDFtoImage package - version 1.2.1, but yeh i even did a clean and rebuild and still no luck.

However I did manage to solve by manually reinstalling your PDFtoImage package, so maybe some setting within nuget for dependancy rules?

**Comment by sungaila** [comment]
Hey @Shovinus, so reinstalling the NuGet package fixed your issue?

I suspect that my [target file for .NET Framework](https://github.com/sungaila/PDFtoImage/blob/master/src/PDFtoImage/PDFtoImage.targets) did not copy the pdfium.dll to the output directory properly. This target file is needed because .NET Framework does not support the runtimes folder introduced in .NET (Core). The file `PDFtoImage.targets` should be found in the `build` folder within the NuGet package.

No idea why it stopped working for you, I will test it with net472 locally just in case.

**Comment by Shovinus** [comment]
So I never initially installed PDFtoImage, I just installed PDFtoZPL, and nuget grabbed PDFtoImage by itself, I then saw that as the .dll for PDFtoImage was missing I should try manually installing that package but reinstalling it. This then gave me the DLL, I am not sure why nuget knew it needed the PDFtoImage package but didn't know to also grab the needed DLL until I manually installed the package.

**Comment by Shovinus** [comment]
OK trying to build an install also doesn't package pdfium.dll even after the reinstall of PDFtoImage
