### ISSUE TITLE
Support for Top/Left offset/adjustment

### ISSUE THREAD

**Issue by JamRob33** [sungaila/PDFtoZPL#62]
### Detailed feature request

Hi @sungaila,
first of all I would like to thank you for that library. It works great in my first tests and looks promising to be used in a project of mine.

Zebra supports some top/left parameters in order to allow some offset adjustment to position a label correctly.
This is beeing applied using the ^LT (Label Top) and/or ^LS (Label Shift) command.
Source: [Zebra - Left and Top position](https://supportcommunity.zebra.com/s/article/Adjusting-Left-Position-and-Top-Position-on-Zebra-Barcode-Printers?language=en_US) 

I was going through current requests/issues but couldn't find such request beeing asked yet.

So I would like to ask, whether its possible to support that in your library.

**Comment by sungaila** [comment]
Hi @JamRob33,

this sounds like a good addition. I'll implement it and will ask you to test it later on.

**Comment by sungaila** [comment]
@JamRob33 I've built a test version with new parameters for `ZplOptions`: 
[NuGet packages.zip](https://github.com/user-attachments/files/16552664/NuGet.packages.zip)

The web converter is updated, too, if you wish to test it there: https://www.sungaila.de/PDFtoZPL/

It looks like a graphic field can be moved down and to the right only. However, I don't have a Zebra printer here and tested on a virtual printer.

**Comment by JamRob33** [comment]
Awesome @sungaila !
Will test on Zebra printer tomorrow and let you know about the results.

**Comment by JamRob33** [comment]
Heya @sungaila,

unfortunately I wasn't able to compile my sample project after exchanging the modified dll you provided due to following error CS1705.

`Assembly 'PDFtoZPL' with identity 'PDFtoZPL, Version=5.3.0.0, Culture=neutral, PublicKeyToken=null' uses 'PDFtoImage, Version=4.1.0.0, Culture=neutral, PublicKeyToken=77810836c31722d8' which has a higher version than referenced assembly 'PDFtoImage' with identity 'PDFtoImage, Version=4.0.2.0, Culture=neutral, PublicKeyToken=77810836c31722d8'`

![image](https://github.com/user-attachments/assets/3bcec850-f08c-402e-bdaf-744a6fe2a114)

In my sample project I installed your NuGet (5.1.0) using NuGet Package Manager.
Then replaced the dll in `C:\Users\myUserName\.nuget\packages\pdftozpl\5.1.0\lib\netstandard2.0` with your modified dll.

![image](https://github.com/user-attachments/assets/87b7435c-a570-46e0-b6e5-659a7da0a030)

I guess I need you to provide me Verison 4.1.0.0 of [PDFtoImage ](https://github.com/sungaila/PDFtoImage) aswell.


This is basically my sample project code:

![image](https://github.com/user-attachments/assets/9fba4c49-907a-4894-8c9a-0e0c629c66c0)

**Comment by sungaila** [comment]
Hi @JamRob33,

there is no need to copy any dlls. You can install [PDFtoImage 4.1.0](https://www.nuget.org/packages/PDFtoImage/4.1.0) and the PDFtoZPL test package via the NuGet package manager.

**Comment by JamRob33** [comment]
Hey @sungaila ,
yes that was my attempt. I had a local package source defined already and pasted the .nupkg there. In the VS Package Manager it didnt want to show me that specific nuget package"PDFtoZPL.5.3.0-ci" for some reason (I have other .nupkg fiiles in there which I could see in VS). Maybe a restart of VS would have helped. However I installed your NuGet from my local package source using the Package Manager **Console**.


I printed now a couple Labels on a real Zebra Printer (model: ZT421).
Your modifications work perfectly. 

As you already mentioned, setting LS values >0 for shifting to the left, take **no effect on a real printer** aswell (asuming position 0 is the top left corner of the label to print). 

![image](https://github.com/user-attachments/assets/4f8729bd-09e0-4724-9a65-c25348853445)
Source: https://supportcommunity.zebra.com/s/article/Adjusting-Left-Position-and-Top-Position-on-Zebra-Barcode-Printers?language=en_US


However, I used that PDF (landscape format) as a sample to print labels:
[OffsetTest.pdf](https://github.com/user-attachments/files/16559732/OffsetTest.pdf)
It's the same size in mm which the printable label has.
The labels have to come out of the printer in portrait format. Therefore I set these PdfOptions in general.
`new PdfOptions(Rotation: PdfRotation.Rotate270);`



The printer I run the tests on seems to have an offset (by default) and does not print the label perfectly centered when
LT = 0 and LS = 0 (or basically those command are not beeing applied).

Values used: **LT=0, LS = 0**
![LT0_LS0](https://github.com/user-attachments/assets/529c15ba-83ca-411f-ac55-dbf2b88243fd)

For a perfect centered label (for that pritner device) I had to use **LT=0, LS = -25**
![LT0_LS-25](https://github.com/user-attachments/assets/a7a8bb9d-b47a-43de-a677-4e7776df3b8e)

I played around with different values in order to see the effect:


**Shift to the left** with values used: **LT=0, LS=30** (no effect, as already mentioned, stays same as LT=0, LS = 0):
![LT0_LS30](https://github.com/user-attachments/assets/535d05fd-4b5d-44ea-b79a-e2c3a8dfde30)

**Shift to the left** with values used: **LT=0, LS=120** (no effect, as already mentioned, stays same as LT=0, LS = 0):
![LT0_LS120](https://github.com/user-attachments/assets/c2030fe7-1a62-4462-84d1-7807a96c57ca)



**Shift to the right** with values used: **LT=0, LS=-30**
![LT0_LS-30](https://github.com/user-attachments/assets/39983b44-ecbe-434d-b062-2a7aa237d5f8)

**Shift to the right** with values used: **LT=0, LS=-60**
![LT0_LS-60](https://github.com/user-attachments/assets/8ab66bb8-e373-486b-a1d6-689912cd88f9)

**Shift to the right** with values used: **LT=0, LS=-90**
![LT0_LS-90](https://github.com/user-attachments/assets/6b0db54c-538c-4665-9f05-08c269a9f268)

**Shift to the right** with values used: **LT=0, LS=-120**
![LT0_LS-120](https://github.com/user-attachments/assets/ddbe417f-9391-4ab8-979b-5221ca8ace0c)



**Move up** with values used: **LT=-50, LS=0**
![LT-50_LS0](https://github.com/user-attachments/assets/032e94f7-10b1-48b2-8279-0b280900b626)

**Move up** with values used: **LT=-50, LS=0**
![LT-100_LS0](https://github.com/user-attachments/assets/7016a603-6c88-468b-8e84-60054fe5ad56)



**Move down* with values used: **LT=50, LS=0**
![LT50_LS0](https://github.com/user-attachments/assets/f8cc3cf8-c903-4b9a-a0b8-fdf84ea7374b)


Conclusion: The library works perefectly fine for my requirements and will definetely be used in a project of mine.

One has to be careful applying LT values >0. For example when I set **LT=100, LS=0** the label sometimes got caught inside the printer (similar to paper jam of normal paper printers). Or the printer throws an error (shown on display) for missing label ribbon due to too the effect, that the next printable label from the ribbon slides off the ribbon roller. That can happen if the printer has a blade built in to automatically tear of printed labels from the ribbon.


It would be great if you could implement another optional ZplOption to be able to adjust the tear-off position (command ~TA, acceptable vlaues -120 ... 120).
![image](https://github.com/user-attachments/assets/2e3f8704-8c7a-4ca0-902c-7bd594164bed)

We do have several printers with an integrated tear-off blade. And sometimes printers require an offset, so the cut between two labels applies perfectly centered, instead of cutting through a labels end. 
I understand that this is might be a very specific requirement and maybe not widely used functionality, but would complete everything to guarantee clean printing (and tear-off functionality). Since that is a bit off-topic I can open a new issue if that is ok for you.

Thanks again for that library and the quick implementation of my request :)

**Comment by sungaila** [comment]
@JamRob33 Thank you for the in-depth testing! I'll publish a new release soon.

>It would be great if you could implement another optional ZplOption to be able to adjust the tear-off position (command ~TA, acceptable vlaues -120 ... 120).

I think this is a bit too out-of-scope for this library. `^LT` and `^LS` make sense since they change the position of the graphic field. `~TA` looks like a printer related setting that won't change the bitmap output by itself.

Maybe you can append `~TA` to the generated ZPL code yourself?

**Comment by JamRob33** [comment]
@sungaila 
You are actually right, it does not really fit the purpose of this library.
I will apply ~TA myself to the generated ZPL string.

**Comment by sungaila** [comment]
@JamRob33 [PDFtoZPL 5.3.0](https://www.nuget.org/packages/PDFtoZPL/5.3.0) has been released. Please reopen this issue if this release isn't working for some reason.

Also thanks again for testing on real hardware!
