### ISSUE TITLE
ZPL can't print some barcodes

### ISSUE THREAD

**Issue by diegodfsd** [sungaila/PDFtoZPL#7]
**Describe the bug**
We are using this lib to convert pdf to zpl format but in some cases when we send zpl data to print the printer can't complete the job print as in the [image](https://ibb.co/SmGjTRD). 
There is no error in the conversion process.

**Stack trace**
No stack trace because there are no error in the processor to convert pdf to zpl

**OS information**
- Which OS? (Windows/Linux/macOS) Linux
- What architecture? (x86/x64/ARM64)  X86_64
- What OS version? (e.g. Windows 10 Version 21H1 or  Debian 10.9) Debian GNU/Linux 10
- For non-Windows: Is libgdiplus installed? Yes

**Sample PDFs/bitmaps/files**
https://ibb.co/SmGjTRD

**Comment by sungaila** [comment]
Hi @diegodfsd,

could you please put the ZPL code into the [Labelary Online ZPL Viewer](http://labelary.com/viewer.html) and see, if your expected output shows up?

If it's broken there as well, then there might be an issue in PDFtoZPL. In that case I would ask you to give me a sample PDF for checking it myself.

**Comment by diegodfsd** [comment]
Hi @sungaila 

Yes, I did this test and in the laberaly online viewer the pdf works fine, but when I send the zpl code to the printer the result is like in the image. Do you have some idea about why this is happening?

**Comment by sungaila** [comment]
Unfortunately, I have no idea how to troubleshoot this. Maybe the printer is not properly calibrated? In your photo the bitmap is correct until a certain line which might indicate that the printer isn't setup for this label size.

Or maybe it is related to the way you send the ZPL commands. Best I could find was this post on the [Zebra support community (via Google Cache)](https://webcache.googleusercontent.com/search?q=cache:_UfF8Lc6towJ:https://supportcommunity.zebra.com/s/question/0D50H00007ulfnFSAQ/printing-from-file-containing-gfa-will-not-print-fd-prints-normally-how-to-get-z64-code-to-print+&cd=2&hl=de&ct=clnk&gl=de):

> Got it working by setting up a linux server to receive the Z64 via POST, create a file with appropriate zpl code, then print via CUPS and "lpr" command.
